FROM amazoncorretto:17-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el JAR de la aplicación al contenedor
COPY target/AppDisco-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto en el que corre Spring Boot (cambiar si usas otro puerto)
EXPOSE 8080

# Comando de ejecución de la aplicación
ENTRYPOINT ["java", "-jar", "/app.jar"]