FROM amazoncorretto:22-alpine-jdk

# Copiar el JAR de la aplicación al contenedor
COPY target/AppDisco-0.0.1-SNAPSHOT.jar app.jar

# Comando de ejecución de la aplicación
ENTRYPOINT ["java", "-jar", "/app.jar"]